version: "3.9"
services:

  postgres:
    image: postgres:13.3
    container_name: postgres_container
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "Uhabr"
      POSTGRES_PASSWORD: "habrpg44"
    volumes:
      - habrdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habrpguser -d habrdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres
      - postgrestest

  postgrestest:
    image: postgres:13.3
    container_name: postgrestest_container
    environment:
      POSTGRES_DB: "testpostgres"
      POSTGRES_USER: "testpostgres"
      POSTGRES_PASSWORD: "testpostgres"
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testpostgres -d testpostgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres
      - postgrestest

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "nburzhik@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "pgadminpwd4habr"
      PGADMIN_DEFAULT_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres
      - postgrestest

volumes:
  habrdb-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge
  postgrestest:
    driver: bridge
    