"""Add message model

Revision ID: fe3f7a5781ff
Revises: a6579ccd139f
Create Date: 2024-02-07 18:35:28.011655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe3f7a5781ff'
down_revision = 'a6579ccd139f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
